# Generated by Django 3.1.7 on 2021-03-28 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0003_auto_20210328_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threadmessage',
            name='parent_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_messages', to='threads.parentmessage'),
        ),
    ]
