# Generated by Django 3.1.7 on 2021-03-29 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0004_auto_20210328_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='parentmessage',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='threads.page'),
        ),
        migrations.AlterField(
            model_name='threadmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
